import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);
  return worker.fetch(new Request("http://localhost/", { headers: { accept: "text/html" } }), { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } }, { waitUntil() {}, passThroughOnException() {} });
}

test("server-renders the Game Garden hub", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  const html = await response.text();
  assert.match(html, /Game Garden/);
  assert.match(html, /Games/);
  assert.match(html, /ゲームガーデン/);
  assert.match(html, /ゲーム/);
  assert.doesNotMatch(html, /POCKET ARCADE|SMALL GAMES|HOW TO PLAY|ポケットアーケード/);
  assert.match(html, /Codebreaker/);
  assert.match(html, /Order Match/);
  assert.match(html, /Number Hunt/);
  assert.match(html, /Memory Flip/);
  assert.match(html, /Connect Four/);
  assert.match(html, /Battleship/);
  assert.match(html, /Dots &amp; Boxes/);
  assert.match(html, /Air Hockey/);
  assert.doesNotMatch(html, /Meducktion|Deducktion/);
  assert.match(html, /App navigation/);
  assert.match(html, /Ranks/);
  assert.match(html, /Profile/);
  assert.match(html, /og-game-garden\.png/);
  assert.doesNotMatch(html, /Pocket Play|POCKET PLAY|ポケットプレイ/);
  assert.doesNotMatch(html, /codex-preview|react-loading-skeleton|Your site is taking shape/i);
});

test("routes every game through a start menu", async () => {
  const source = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const styles = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  const onlineSource = await readFile(new URL("../app/online-games.tsx", import.meta.url), "utf8");
  const battleshipSource = await readFile(new URL("../app/battleship-game.tsx", import.meta.url), "utf8");
  const dotsBoxesSource = await readFile(new URL("../app/dots-boxes-game.tsx", import.meta.url), "utf8");
  const gameResultSource = await readFile(new URL("../app/game-result.tsx", import.meta.url), "utf8");
  const airHockeySource = await readFile(new URL("../app/air-hockey-game.tsx", import.meta.url), "utf8");
  const onlineAirHockeySource = await readFile(new URL("../app/online-air-hockey.tsx", import.meta.url), "utf8");
  const barricadeDragSource = await readFile(new URL("../app/barricade-drag.tsx", import.meta.url), "utf8");
  const chatSource = await readFile(new URL("../app/chat-chrome.tsx", import.meta.url), "utf8");
  const onlineStyles = await readFile(new URL("../app/online-games.css", import.meta.url), "utf8");
  const firebaseSource = await readFile(new URL("../app/firebase.ts", import.meta.url), "utf8");
  const firestoreRules = await readFile(new URL("../firestore.rules", import.meta.url), "utf8");
  assert.match(source, /codebreaker-menu/);
  assert.match(source, /order-menu/);
  assert.match(source, /number-menu/);
  assert.match(source, /memory-menu/);
  assert.match(source, /tictactoe-menu/);
  assert.match(source, /connect4-menu/);
  assert.match(source, /rps-menu/);
  assert.match(source, /dice-menu/);
  assert.match(source, /battleship-menu/);
  assert.match(source, /dotsboxes-menu/);
  assert.match(source, /airhockey-menu/);
  assert.doesNotMatch(source, /meducktion|deducktion/i);
  assert.match(source, /function GameMenu/);
  assert.match(source, /Open Lobby/);
  assert.match(source, /type GameMode = "solo" \| "multi"/);
  assert.match(source, /className="mode-picker"/);
  assert.match(source, /VERSUS<small>2 PLAYERS/);
  assert.match(source, /function TurnBanner/);
  assert.match(source, /function GameLobby/);
  assert.match(source, /type GameRoom/);
  assert.match(source, /roomCodeFromUrl/);
  assert.match(source, /makeRoomCode/);
  assert.match(source, /signInAnonymously/);
  assert.match(source, /CREATE ROOM/);
  assert.match(source, /JOIN ROOM/);
  assert.match(source, /SHARE LINK/);
  assert.match(source, /COPY LINK/);
  assert.match(source, /searchParams\.set\("room"/);
  assert.match(source, /VERSUS LOBBY · 対戦ロビー/);
  assert.match(source, /Invite friends/);
  assert.match(source, />Accept<\/button>/);
  assert.match(source, /Start Online Versus/);
  assert.match(source, /onJoinLobby/);
  assert.match(source, /`\$\{gameId\}-lobby`/);
  assert.match(source, /<OnlineVersusGame/);
  assert.match(source, /makeOnlineGameState/);
  assert.match(source, /nextRoom\.status === "playing"/);
  assert.match(onlineSource, /export function OnlineVersusGame/);
  assert.match(onlineSource, /runTransaction/);
  assert.match(onlineSource, /onSnapshot/);
  assert.match(onlineSource, /await updateDoc\(stateRef/);
  assert.match(onlineSource, /latestState\.current = optimistic/);
  for (const gameId of ["codebreaker", "order", "memory", "tictactoe", "connect4", "rps", "dice", "checkers", "battleship", "dotsboxes", "airhockey"]) assert.match(onlineSource, new RegExp(`state\\.gameId === "${gameId}"`));
  assert.match(source, /How to play/);
  assert.match(source, /aria-label="Close game menu"/);
  assert.match(source, /className="menu-close"/);
  assert.match(source, /<div className="menu-card">\s*<button className="menu-close"/);
  assert.match(source, /function OrderMatch/);
  assert.match(source, /function NumberHunt/);
  assert.match(source, /function OnlineNumberHunt/);
  assert.match(source, /NumberOnlineState/);
  assert.match(source, /YOUR PRIVATE SCREEN/);
  assert.match(source, /Waiting for clue/);
  assert.match(source, /status: "playing"/);
  assert.match(source, /type NumberVersusPhase/);
  assert.match(source, /Choose the secret/);
  assert.match(source, /SECRET LOCKED/);
  assert.match(source, /Pass to Player/);
  assert.match(source, /Swap Roles/);
  assert.match(source, /Fewest guesses wins/);
  assert.match(source, /function TicTacToe/);
  assert.match(source, /type CpuDifficulty = "easy" \| "normal" \| "hard"/);
  assert.match(source, /function CpuDifficultyPicker/);
  assert.match(source, /function ticMinimax/);
  assert.match(source, /cpuTicMove\(next, difficulty\)/);
  assert.match(source, /初級/);
  assert.match(source, /中級/);
  assert.match(source, /上級/);
  assert.match(source, /function ConnectFour/);
  assert.match(source, /function connectCpuMove/);
  assert.match(source, /const CONNECT_CPU_LEVELS/);
  assert.match(source, /easy: \{ winChance: 0\.65/);
  assert.match(source, /hard: \{ winChance: 1, blockChance: 1, randomChance: 0, depth: 4/);
  assert.match(source, /connectCpuMove\(board, difficulty\)/);
  assert.match(source, /connect-column-controls/);
  assert.match(source, /<button type="button" role="gridcell"/);
  assert.match(source, /preview-slot preview-/);
  assert.match(source, /winning-piece/);
  assert.match(source, /function RockPaperScissors/);
  assert.match(source, /type RpsRound/);
  assert.match(source, /rps-arena \$\{lastRound/);
  assert.match(source, /className="rps-score-pips"/);
  assert.match(source, /className="rps-round-history"/);
  assert.match(source, /じゃんけん/);
  assert.match(source, /function DiceRace/);
  assert.match(source, /function Barricade/);
  assert.match(source, /function Checkers/);
  assert.match(source, /<GameMenu game="checkers"/);
  assert.match(source, /recordScore\("checkers", score\)/);
  assert.match(source, /const \[lastMove, setLastMove\]/);
  assert.match(onlineSource, /playCheckers/);
  assert.match(onlineSource, /lastCheckersMove/);
  assert.match(styles, /\.checkers-board/);
  assert.match(styles, /\.checkers-piece\.move-arrival/);
  assert.match(styles, /@keyframes checkersMove/);
  assert.match(styles, /@keyframes checkersCapture/);
  assert.match(styles, /game-checkers\.png/);
  assert.match(source, /<GameMenu game="battleship"/);
  assert.match(source, /recordScore\("battleship", score\)/);
  assert.match(battleshipSource, /export function Battleship/);
  assert.match(battleshipSource, /<BattleshipPlacement/);
  assert.match(battleshipSource, /chooseBattleshipCpuShot/);
  assert.match(battleshipSource, /onPointerDown=\{\(event\) => beginDrag/);
  assert.match(battleshipSource, /onPointerMove=\{\(event\) => moveDrag/);
  assert.match(battleshipSource, /onPointerUp=\{\(event\) => finishDrag/);
  assert.match(battleshipSource, /onShipPointerDown=\{beginBoardDrag\}/);
  assert.match(battleshipSource, /ship-drop-preview/);
  assert.match(onlineSource, /readyBattleshipFleet/);
  assert.match(onlineSource, /fireBattleship/);
  assert.match(styles, /\.battleship-grid/);
  assert.match(styles, /\.battleship-drag-ghost/);
  assert.match(styles, /\.ship-drop-preview/);
  assert.match(styles, /game-battleship\.png/);
  assert.match(source, /<GameMenu game="dotsboxes"/);
  assert.match(source, /recordScore\("dotsboxes", score\)/);
  assert.match(dotsBoxesSource, /export function DotsBoxesBoard/);
  assert.match(dotsBoxesSource, /chooseDotsBoxesCpuEdge/);
  assert.match(onlineSource, /playDotsBoxes/);
  assert.match(styles, /\.dots-boxes-board/);
  assert.match(styles, /game-dots-boxes\.png/);
  assert.match(gameResultSource, /MATCH WINNER/);
  assert.match(gameResultSource, /PLAY AGAIN/);
  assert.match(gameResultSource, /aria-live="assertive"/);
  assert.match(styles, /\.game-result-banner/);
  assert.match(styles, /\.game-result-replay/);
  assert.match(source, /<GameResult outcome=/);
  assert.match(onlineSource, /const finish = <GameResult/);
  assert.match(battleshipSource, /<GameResult outcome=/);
  assert.match(dotsBoxesSource, /<GameResult outcome=/);
  assert.match(source, /<GameMenu game="airhockey"/);
  assert.match(source, /recordScore\("airhockey", score\)/);
  assert.match(airHockeySource, /export function AirHockeyRink/);
  assert.match(airHockeySource, /stepAirHockeyLive/);
  assert.match(airHockeySource, /moveAirHockeyCpu/);
  assert.match(airHockeySource, /requestAnimationFrame/);
  assert.doesNotMatch(airHockeySource, /setDisplayPuck|setDisplayMallets/);
  assert.match(airHockeySource, /LOCK RINK/);
  assert.match(airHockeySource, /AirHockeyFullscreenScoreboard/);
  assert.match(airHockeySource, /AirHockeyMatchOverlay/);
  assert.match(airHockeySource, /PLAY AGAIN/);
  assert.match(airHockeySource, /EXIT RINK/);
  assert.match(airHockeySource, /FIRST TO 3/);
  assert.match(airHockeySource, /airHockeyClock/);
  assert.doesNotMatch(airHockeySource, /UNLOCK SCREEN/);
  assert.match(airHockeySource, /PUCK LIVE/);
  assert.doesNotMatch(airHockeySource, /PULL PUCK|beginPull|movePull|releasePull/);
  assert.match(onlineSource, /OnlineAirHockeyRink/);
  assert.match(onlineSource, /SIMULTANEOUS ONLINE/);
  assert.doesNotMatch(onlineSource, /Each shot synchronizes/);
  assert.match(onlineAirHockeySource, /requestAnimationFrame/);
  assert.doesNotMatch(onlineAirHockeySource, /setDisplayPuck|setDisplayMallets/);
  assert.match(onlineAirHockeySource, /BOTH PLAYERS LIVE/);
  assert.match(onlineAirHockeySource, /AirHockeyFullscreenScoreboard/);
  assert.match(onlineAirHockeySource, /AirHockeyMatchOverlay/);
  assert.match(onlineAirHockeySource, /stepAirHockeyLive/);
  assert.match(firestoreRules, /validLiveAirHockeyMallet/);
  assert.match(styles, /\.air-hockey-rink/);
  assert.match(styles, /\.live-rink \.air-mallet\.is-controlled\{transition:none\}/);
  assert.match(styles, /\.air-fullscreen-scoreboard/);
  assert.match(styles, /\.air-fullscreen-close/);
  assert.match(styles, /\.air-match-overlay/);
  assert.match(styles, /\.air-match-replay/);
  assert.match(styles, /game-air-hockey\.png/);
  assert.match(source, /function chooseBarricadeCpuAction/);
  assert.match(source, /playerCanWinNext/);
  assert.match(source, /blocksWin \? 120/);
  assert.match(source, /barricadeBestReplyPath/);
  assert.match(source, /rankedWalls\.find\(\(choice\) => choice\.blocksWin\)/);
  assert.match(source, /chooseBarricadeCpuAction\(positions, walls, wallsLeft\[1\], difficulty\)/);
  assert.match(source, /className="quoridor-board"/);
  assert.match(source, /legalBarricadeWall/);
  assert.match(onlineSource, /onlineBarricadeMoves/);
  assert.match(onlineSource, /placeBarricade/);
  assert.doesNotMatch(source, /<BarricadeDragPiece kind="pawn"/);
  assert.doesNotMatch(onlineSource, /<BarricadeDragPiece kind="pawn"/);
  assert.match(source, /<BarricadeDragPiece kind="h"/);
  assert.match(source, /<BarricadeDragPiece kind="v"/);
  assert.match(source, /onClick=\{\(\) => movePawn\(0, index\)\}/);
  assert.match(onlineSource, /onClick=\{\(\) => moveBarricadePawn\(index\)\}/);
  assert.match(source, /TAP A SPACE OR DRAG A WALL/);
  assert.match(styles, /\/\* Barricade app board \*\//);
  assert.match(styles, /barricade-drag-piece\.drag-h::after\{content:"Horizontal"\}/);
  assert.match(styles, /quoridor-cells \.pawn-two\{background:#3f87ff\}/);
  assert.match(source, /onDragMove=\{previewBarricadeWall\}/);
  assert.match(onlineSource, /onDragMove=\{previewOnlineBarricadeWall\}/);
  assert.match(barricadeDragSource, /clientX \+ 22, y: clientY - 58/);
  assert.match(barricadeDragSource, /onDragMove\?\.\(point\.x, point\.y, kind\)/);
  assert.match(styles, /art-barricade[^}]*game-barricade-v2\.png/);
  assert.match(styles, /wall-target\.snap-preview\.legal/);
  assert.match(styles, /wall-target\.snap-preview\.blocked/);
  assert.match(styles, /wall-target\.legal:not\(\.snap-preview\)\{background:transparent;box-shadow:none\}/);
  assert.match(onlineSource, /dropOnlineBarricadePiece/);
  assert.match(barricadeDragSource, /onPointerDown/);
  assert.match(barricadeDragSource, /onPointerMove/);
  assert.match(barricadeDragSource, /onPointerUp/);
  assert.doesNotMatch(source, /className="barricade-action-bar"/);
  assert.doesNotMatch(onlineSource, /className="barricade-action-bar"/);
  assert.match(source, /switchObject/);
  assert.match(source, /Check order/);
  assert.match(source, /pocket-play-scores/);
  assert.match(source, /game-garden-account-\$\{user\.uid\}-\$\{field\}/);
  assert.match(source, /authLoadId\.current !== loadId/);
  assert.match(source, /Reset this profile's scores/);
  assert.match(styles, /\.reset-scores-button/);
  assert.match(styles, /\.score-art\s*\{[^}]*position:relative;[^}]*overflow:hidden;[^}]*contain:paint;/);
  assert.match(source, /function AppHome/);
  assert.match(source, /function PlayerAvatar/);
  assert.match(source, /activeTab === "leaderboard"/);
  assert.match(source, /activeTab === "profile"/);
  assert.match(source, /activeTab === "friends"/);
  assert.match(source, /YOUR FRIEND CODE/);
  assert.match(source, /friendCodeFor/);
  assert.match(source, /friendCodeFromUrl/);
  assert.match(source, /Share friend link/);
  assert.match(source, /className="friend-connect-card"/);
  assert.match(source, /className="friend-connect-code"/);
  assert.match(source, /className="friend-connect-add"/);
  assert.match(source, /className="friends-account-banner"/);
  assert.match(source, /className="friends-signin-emblem"/);
  assert.doesNotMatch(source, /avatarId="pink-blossom" className="friend-hero-avatar"/);
  assert.match(source, /className="friends-account-avatar"><PlayerAvatar avatarId=\{avatarId\}/);
  assert.match(source, /className=\{`friend-banner/);
  assert.match(source, /Search friends by name/);
  assert.match(source, /profile details/);
  assert.match(source, /VIEW PROFILE/);
  assert.doesNotMatch(source, /className="friend-tools-grid"/);
  assert.match(styles, /\.friend-connect-card\s*\{[^}]*grid-template-columns:\.92fr 1\.08fr;[^}]*overflow:hidden;/);
  assert.match(source, /navigator\.share/);
  assert.match(source, /navigator\.clipboard/);
  assert.match(source, /searchParams\.set\("friend"/);
  assert.match(source, /publicProfiles/);
  assert.match(source, /onAddFriend/);
  assert.match(source, /Continue with Google/);
  assert.match(source, /Create account/);
  assert.match(source, /signInWithEmailAndPassword/);
  assert.match(source, /createUserWithEmailAndPassword/);
  assert.match(source, /Choose a profile picture/);
  assert.match(source, /aria-label="Change color mode"[^>]*><span>MODE<\/span><\/button>/);
  assert.match(source, /game-garden-theme/);
  assert.match(source, /avatar-style-/);
  const avatarOptions = source.match(/const AVATARS[\s\S]*?\n\];/)?.[0] ?? "";
  assert.equal((avatarOptions.match(/id: "/g) ?? []).length, 24);
  assert.equal((avatarOptions.match(/premium: true/g) ?? []).length, 9);
  assert.equal((avatarOptions.match(/glyph: "/g) ?? []).length, 2);
  assert.match(source, /avatar\.glyph && <b className="avatar-mark">/);
  assert.match(source, /className="header-profile"/);
  assert.match(source, /const signedIn = Boolean\(firebaseUser && !firebaseUser\.isAnonymous\)/);
  assert.match(source, /className="header-signin-button"/);
  assert.match(source, /className="profile-signin-only"/);
  assert.match(source, /signedIn && <div className="score-list">/);
  assert.match(source, /signedIn \? <div className="player-rank-card">/);
  assert.match(source, /className="profile-dropdown" role="menu"/);
  assert.match(source, />Profile<\/span>/);
  assert.match(source, />Leaderboard<\/span>/);
  assert.match(source, />Friends<\/span>/);
  assert.match(source, />Invites<\/span>/);
  assert.match(source, /aria-haspopup="menu"/);
  assert.match(source, /event\.key === "Escape"/);
  assert.match(source, /id="game-invites"/);
  assert.match(styles, /\.profile-dropdown\s*\{[^}]*position:absolute;[^}]*z-index:60;/);
  assert.match(styles, /\.header-signin-button/);
  assert.match(styles, /\.profile-signin-only/);
  assert.match(styles, /\.rank-signin-card/);
  assert.match(styles, /@keyframes profileMenuIn/);
  assert.match(source, /<PlayerAvatar small avatarId=\{avatarId\} \/>/);
  assert.doesNotMatch(styles, /\.header-profile>i/);
  assert.match(source, /onAuthStateChanged/);
  assert.match(source, /saveCloudScore/);
  assert.match(source, /<p>GLOBAL<\/p><h1>Leaderboard/);
  assert.doesNotMatch(styles, /meducktion|deducktion/i);
  assert.match(styles, /game-covers\.png/);
  assert.match(styles, /game-connect4\.png/);
  assert.match(styles, /\.bottom-nav/);
  assert.match(styles, /\.theme-toggle[^}]*box-shadow:none/);
  assert.match(styles, /\.theme-toggle[^}]*linear-gradient\(135deg,#ff001e/);
  assert.match(styles, /\.avatar-style-fox::before/);
  assert.match(styles, /\.avatar-style-pink-heart::before/);
  assert.match(styles, /premium-avatars\.webp/);
  assert.match(source, /premium-cat/);
  assert.match(source, /premium-blossom/);
  assert.match(source, /premium-dual-swords/);
  assert.match(styles, /premium-cat-v3\.jpg/);
  assert.match(styles, /premium-blossom\.jpg/);
  assert.match(styles, /premium-dual-swords-v2\.jpg/);
  assert.match(styles, /\.avatar-premium/);
  assert.doesNotMatch(styles, /\.avatar-premium::after|♛/);
  assert.match(styles, /\.premium-avatar-picker/);
  assert.match(source, /className="profile-avatar-button"/);
  assert.match(source, /className="profile-avatar-label"/);
  assert.match(styles, /\.profile-avatar-button>\.profile-avatar-label/);
  assert.doesNotMatch(styles, /\.profile-avatar-button>span\s*\{/);
  assert.match(source, /avatarPickerOpen &&/);
  assert.match(source, /role="dialog" aria-modal="true"/);
  assert.match(styles, /\.avatar-picker-backdrop/);
  assert.match(source, /const PREMIUM_ACCESS_CODE = "SOKEY"/);
  assert.match(source, /premiumUnlocked/);
  assert.match(source, /onUnlockPremium/);
  assert.match(source, /Premium unlocked for this account/);
  assert.match(source, /className="store-code-form"/);
  assert.match(source, /className="store-coming-card"/);
  assert.match(source, /Items coming soon\./);
  assert.doesNotMatch(source, /Codes, drops &amp; rewards|Legendary Icons|Seasonal drops/);
  assert.match(source, /activeTab === "store"/);
  assert.match(source, /<details className="profile-stats-menu">/);
  assert.match(source, /Stats &amp; high scores/);
  assert.match(styles, /\.premium-access-card/);
  assert.match(styles, /\.premium-avatar-picker button\.locked::after/);
  assert.match(styles, /\.profile-stats-menu/);
  assert.match(styles, /\.profile-stats-menu \{ box-shadow:none; \}/);
  assert.match(styles, /\.theme-toggle\[aria-pressed="true"\][^}]*linear-gradient\(#0d0d0d,#0d0d0d\) padding-box/);
  assert.match(styles, /\.friend-link-actions/);
  assert.match(styles, /\.friends-panel \.app-title h1[^}]*color:var\(--red\)/);
  assert.match(styles, /\.invite-center-heading[^}]*color:var\(--red\)/);
  assert.match(styles, /\.friend-list-heading[^}]*color:var\(--red\)/);
  assert.match(styles, /\.global-rank-list/);
  assert.match(styles, /\.bottom-nav[^}]*position:fixed;inset:auto 0 0/);
  assert.match(styles, /\.bottom-nav[^}]*height:83px/);
  assert.match(styles, /\.bottom-nav\{height:76px/);
  assert.match(styles, /\.bottom-nav \{[^}]*width:100vw;[^}]*grid-template-columns:repeat\(5,minmax\(0,152px\)\);[^}]*border-top:5px solid var\(--red\)/);
  assert.doesNotMatch(styles, /\.bottom-nav::before/);
  assert.match(styles, /\.bottom-nav button\.active b \{ border-color:transparent;background:transparent;color:var\(--red\);box-shadow:none;/);
  assert.doesNotMatch(styles, /\.bottom-nav button\.active b \{[^}]*border-color:white/);
  assert.match(styles, /\.app-shell[^}]*min-height:100svh/);
  assert.match(styles, /\.friend-list/);
  assert.match(styles, /\.friends-account-banner/);
  assert.match(styles, /:root\[data-theme="sakura"\] \.friends-signin-card h2\{color:#e4316b!important\}/);
  assert.match(styles, /\.friends-signin-emblem/);
  assert.match(styles, /\.friends-account-banner,\.friend-list\.friend-list-primary\{box-shadow:none\}/);
  assert.match(styles, /\.friend-banner-profile/);
  assert.match(styles, /\.friend-score-grid/);
  assert.match(source, /function FriendsChat/);
  assert.match(source, /collection\(db, "directChats"\)/);
  assert.match(source, /where\("participants", "array-contains", user\.uid\)/);
  assert.match(chatSource, /className=\{`header-chat/);
  assert.match(source, /className="friend-chat-button"/);
  assert.match(source, /lastActiveAt: serverTimestamp\(\)/);
  assert.match(styles, /\.friends-social-hero/);
  assert.match(styles, /\.chat-window/);
  assert.match(styles, /\.friend-avatar-wrap>i\.online/);
  assert.match(styles, /\.mode-picker/);
  assert.match(styles, /\.turn-banner/);
  assert.match(styles, /\.game-lobby/);
  assert.match(styles, /\.lobby-players/);
  assert.match(styles, /\.lobby-friends/);
  assert.match(styles, /\.lobby-entry-grid/);
  assert.match(styles, /\.room-share-card/);
  assert.match(styles, /\.tic-board/);
  assert.match(styles, /\.cpu-difficulty/);
  assert.match(styles, /\.difficulty-options button\.active/);
  assert.match(styles, /\.number-versus-progress/);
  assert.match(styles, /\.number-role-card/);
  assert.match(styles, /\.number-match-scores/);
  assert.match(styles, /\.online-match-heading/);
  assert.match(styles, /@keyframes onlinePulse/);
  assert.match(styles, /\.connect-board/);
  assert.match(styles, /@keyframes connectDrop/);
  assert.doesNotMatch(styles, /72%\{transform:translateY\(8px\)/);
  assert.match(styles, /\.rps-choices/);
  assert.match(styles, /\.rps-arena/);
  assert.match(styles, /@keyframes rpsWinnerPop/);
  assert.match(styles, /@keyframes rpsImpact/);
  assert.match(styles, /\.dice-racers/);
  assert.match(onlineStyles, /\.online-player-strip/);
  assert.match(onlineStyles, /\.online-turn-status/);
  assert.match(firestoreRules, /'tictactoe', 'connect4', 'rps', 'dice', 'barricade', 'checkers', 'battleship', 'dotsboxes', 'airhockey'/);
  assert.match(firestoreRules, /gameId == 'checkers' && gameName == 'Checkers'/);
  assert.match(firestoreRules, /gameId == 'battleship' && gameName == 'Battleship'/);
  assert.match(firestoreRules, /gameId == 'dotsboxes' && gameName == 'Dots & Boxes'/);
  assert.match(firestoreRules, /gameId == 'airhockey' && gameName == 'Air Hockey'/);
  assert.match(firestoreRules, /request\.auth\.uid == resource\.data\.fromUid\s*\|\| request\.auth\.uid == resource\.data\.toUid/);
  assert.doesNotMatch(firestoreRules, /allow read: if request\.auth != null\s*&& request\.auth\.uid in \[resource\.data\.fromUid, resource\.data\.toUid\]/);
  assert.match(source, /friendProfiles/);
  assert.match(source, /selectedFriend\.highScores/);
  assert.match(source, /friendRequests/);
  assert.match(source, /onRespondFriendRequest/);
  assert.match(source, /type InviteStatus = "pending" \| "accepted" \| "declined" \| "cancelled"/);
  assert.match(source, /inviteIdFor/);
  assert.match(source, /Game invites/);
  assert.match(source, /onRespondInvite/);
  assert.match(source, /ROOM READY/);
  assert.match(source, /nav-invite-badge/);
  assert.match(source, /const HEADER_META/);
  assert.match(source, /header-title-logo/);
  assert.match(source, /function HeaderLogo/);
  assert.equal((source.match(/<HeaderLogo compact \/>/g) ?? []).length, 13);
  assert.match(source, /<button className="header-brand"[\s\S]*?<HeaderLogo \/>/);
  assert.doesNotMatch(source, /wordmark small-wordmark/);
  assert.match(source, /className="header-context"/);
  assert.match(source, /className="app-error-banner"/);
  assert.match(styles, /\.invite-center/);
  assert.match(styles, /\.friend-invite-picker/);
  assert.match(styles, /\.header-invites/);
  assert.match(styles, /\.header-online/);
  assert.match(styles, /game-garden-logo-red\.png/);
  assert.match(styles, /game-garden-logo-pink\.png/);
  assert.match(styles, /\.game-header-logo/);
  assert.match(styles, /\.barricade-game-shell>\.game-topbar\{color:var\(--black\)\}/);
  assert.match(styles, /\.grid-barricade \.difficulty-options button>span\{color:var\(--black\)\}/);
  assert.equal((styles.match(/\.hub-nav\{height:65px/g) ?? []).length, 1);
  assert.match(styles, /data-theme="sakura"/);
  assert.match(styles, /content:"桜"/);
  assert.doesNotMatch(styles, /data-theme="sakura"[^}]*\.bottom-nav[^}]*position:relative/);
  assert.match(firebaseSource, /game-garden-658de/);
  assert.match(firestoreRules, /request\.auth\.uid == userId/);
  assert.match(firestoreRules, /premiumUnlocked is bool/);
  assert.match(firestoreRules, /validAccountAvatar/);
  assert.match(firestoreRules, /isPremiumAvatar/);
  assert.match(firestoreRules, /publicProfiles/);
  assert.match(firestoreRules, /highScores is map/);
  assert.match(firestoreRules, /users\/\{userId\}\/friends/);
  assert.match(firestoreRules, /directChats\/\{chatId\}/);
  assert.match(firestoreRules, /messages\/\{messageId\}/);
  assert.match(firestoreRules, /validNewDirectChat/);
  assert.match(firestoreRules, /getAfter/);
  assert.match(firestoreRules, /invites\/\{inviteId\}/);
  assert.match(firestoreRules, /validNewInvite/);
  assert.match(firestoreRules, /rooms\/\{roomCode\}/);
  assert.match(firestoreRules, /validNewRoom/);
  assert.match(firestoreRules, /validRoomCode/);
  assert.match(firestoreRules, /numberHunt/);
  assert.match(firestoreRules, /validNumberState/);
  assert.match(firestoreRules, /rooms\/\{roomCode\}\/game\/\{documentId\}/);
  assert.match(firestoreRules, /validOnlineGameState/);
  assert.match(firestoreRules, /roomParticipant/);
  assert.match(firestoreRules, /affectedKeys\(\)\.hasOnly/);
  assert.match(firestoreRules, /'sakura'.*'dragon'.*'pink-blossom'.*'pink-peach'/);
  assert.match(firestoreRules, /'premium-cat', 'premium-blossom', 'premium-dual-swords'/);
});
