import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);
  return worker.fetch(new Request("http://localhost/", { headers: { accept: "text/html" } }), { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } }, { waitUntil() {}, passThroughOnException() {} });
}

test("server-renders the Game Garden hub", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  const html = await response.text();
  assert.match(html, /Game Garden/);
  assert.match(html, /Games/);
  assert.match(html, /ゲームガーデン/);
  assert.match(html, /ゲーム/);
  assert.doesNotMatch(html, /POCKET ARCADE|SMALL GAMES|HOW TO PLAY|ポケットアーケード/);
  assert.match(html, /Codebreaker/);
  assert.match(html, /Order Match/);
  assert.match(html, /Number Hunt/);
  assert.match(html, /Memory Flip/);
  assert.match(html, /Meducktion/);
  assert.match(html, /Deducktion/);
  assert.match(html, /App navigation/);
  assert.match(html, /Ranks/);
  assert.match(html, /Profile/);
  assert.match(html, /og-game-garden\.png/);
  assert.doesNotMatch(html, /Pocket Play|POCKET PLAY|ポケットプレイ/);
  assert.doesNotMatch(html, /codex-preview|react-loading-skeleton|Your site is taking shape/i);
});

test("routes every game through a start menu", async () => {
  const source = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const styles = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  const firebaseSource = await readFile(new URL("../app/firebase.ts", import.meta.url), "utf8");
  const firestoreRules = await readFile(new URL("../firestore.rules", import.meta.url), "utf8");
  assert.match(source, /codebreaker-menu/);
  assert.match(source, /order-menu/);
  assert.match(source, /number-menu/);
  assert.match(source, /memory-menu/);
  assert.match(source, /meducktion-menu/);
  assert.match(source, /deducktion-menu/);
  assert.match(source, /function GameMenu/);
  assert.match(source, /Start \{supportsLocalMultiplayer/);
  assert.match(source, /type GameMode = "solo" \| "multi"/);
  assert.match(source, /className="mode-picker"/);
  assert.match(source, /VERSUS<small>2 PLAYERS/);
  assert.match(source, /function TurnBanner/);
  assert.match(source, /mode=\{gameMode\}/);
  assert.match(source, /How to play/);
  assert.match(source, /aria-label="Close game menu"/);
  assert.match(source, /className="menu-close"/);
  assert.match(source, /<div className="menu-card">\s*<button className="menu-close"/);
  assert.match(source, /function OrderMatch/);
  assert.match(source, /switchObject/);
  assert.match(source, /Check order/);
  assert.match(source, /pocket-play-scores/);
  assert.match(source, /function AppHome/);
  assert.match(source, /function PlayerAvatar/);
  assert.match(source, /activeTab === "leaderboard"/);
  assert.match(source, /activeTab === "profile"/);
  assert.match(source, /activeTab === "friends"/);
  assert.match(source, /YOUR FRIEND CODE/);
  assert.match(source, /friendCodeFor/);
  assert.match(source, /friendCodeFromUrl/);
  assert.match(source, /Share friend link/);
  assert.match(source, /navigator\.share/);
  assert.match(source, /navigator\.clipboard/);
  assert.match(source, /searchParams\.set\("friend"/);
  assert.match(source, /publicProfiles/);
  assert.match(source, /onAddFriend/);
  assert.match(source, /Continue with Google/);
  assert.match(source, /Create account/);
  assert.match(source, /signInWithEmailAndPassword/);
  assert.match(source, /createUserWithEmailAndPassword/);
  assert.match(source, /Choose a profile picture/);
  assert.match(source, /Toggle Sakura Mode/);
  assert.match(source, /game-garden-theme/);
  assert.match(source, /avatar-style-/);
  const avatarOptions = source.match(/const AVATARS[\s\S]*?\n\];/)?.[0] ?? "";
  assert.equal((avatarOptions.match(/glyph: "/g) ?? []).length, 15);
  assert.match(source, /onAuthStateChanged/);
  assert.match(source, /saveCloudScore/);
  assert.match(source, /<p>GLOBAL<\/p><h1>Leaderboard/);
  assert.match(source, /function EmbeddedGame/);
  assert.match(source, /keshawn7b\.github\.io\/Meducktion/);
  assert.match(source, /keshawn7b\.github\.io\/deduction-game/);
  assert.match(source, /deducktion-cover-title">DEDUCKTION/);
  assert.match(source, /name: "Deducktion"[\s\S]*?meta: "CARD GAME"/);
  assert.match(styles, /game-covers\.png/);
  assert.match(styles, /\.bottom-nav/);
  assert.match(styles, /\.friend-link-actions/);
  assert.match(styles, /\.friends-panel \.app-title h1[^}]*color:var\(--red\)/);
  assert.match(styles, /\.invite-center-heading[^}]*color:var\(--red\)/);
  assert.match(styles, /\.friend-list-heading[^}]*color:var\(--red\)/);
  assert.match(styles, /\.global-rank-list/);
  assert.match(styles, /\.friend-list/);
  assert.match(styles, /\.friend-score-grid/);
  assert.match(styles, /\.mode-picker/);
  assert.match(styles, /\.turn-banner/);
  assert.match(source, /friendProfiles/);
  assert.match(source, /friend\.highScores/);
  assert.match(source, /type InviteStatus = "pending" \| "accepted" \| "declined" \| "cancelled"/);
  assert.match(source, /inviteIdFor/);
  assert.match(source, /Game invites/);
  assert.match(source, /onRespondInvite/);
  assert.match(source, /ROOM READY/);
  assert.match(source, /nav-invite-badge/);
  assert.match(source, /const HEADER_META/);
  assert.match(source, /className="header-title-logo"/);
  assert.match(source, /className="header-context"/);
  assert.match(source, /className="app-error-banner"/);
  assert.match(styles, /\.invite-center/);
  assert.match(styles, /\.friend-invite-picker/);
  assert.match(styles, /\.header-invites/);
  assert.match(styles, /\.header-online/);
  assert.match(styles, /game-garden-logo-red\.png/);
  assert.match(styles, /game-garden-logo-pink\.png/);
  assert.equal((styles.match(/\.hub-nav\{height:65px/g) ?? []).length, 1);
  assert.match(styles, /data-theme="sakura"/);
  assert.match(styles, /content:"桜"/);
  assert.doesNotMatch(styles, /data-theme="sakura"[^}]*\.bottom-nav[^}]*position:relative/);
  assert.match(firebaseSource, /game-garden-658de/);
  assert.match(firestoreRules, /request\.auth\.uid == userId/);
  assert.match(firestoreRules, /publicProfiles/);
  assert.match(firestoreRules, /highScores is map/);
  assert.match(firestoreRules, /users\/\{userId\}\/friends/);
  assert.match(firestoreRules, /invites\/\{inviteId\}/);
  assert.match(firestoreRules, /validNewInvite/);
  assert.match(firestoreRules, /affectedKeys\(\)\.hasOnly/);
  assert.match(firestoreRules, /'sakura'.*'dragon'.*'pink-blossom'.*'pink-peach'/);
});
